function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 11-May-2022 12:56:26

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'MarkerSize',4,'Marker','.',...
    'LineStyle','none');

% Create ylabel
ylabel('Amplitude [ V ]');

% Create xlabel
xlabel('Time [ sec ]');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-5.22353517317018e-07 6.8246360642115e-07]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.0177186623330443 0.00374575564524038]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','AvantGarde','FontSize',16,'LineWidth',2);
