function [tabularData, opts] = readLECROYWaveRunnerkR(filename)
%% Import data from text file
% Script for importing data from the following text file:
%
%
% Auto-generated by MATLAB on 10-May-2022 16:08:26

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [6, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Time", "Ampl1", "Ampl2", "Ampl3", "Ampl4"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
tabularData = readtable(filename, opts);

%% Clear temporary variables
%clear opts